# Generated by Django 4.1.4 on 2023-01-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Consulat',
            fields=[
                ('NumAgent', models.AutoField(primary_key=True, serialize=False)),
                ('Matricule', models.CharField(max_length=10, null=True)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('photo', models.CharField(max_length=50, null=True)),
                ('NumSupAgent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatSevApp.agent_consulat')),
            ],
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('NumB', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commune', models.CharField(max_length=50)),
                ('Daira', models.CharField(max_length=50)),
                ('Wilaya', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consulat',
            fields=[
                ('NumB', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Paye', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Officier',
            fields=[
                ('NumOff', models.AutoField(primary_key=True, serialize=False)),
                ('Matricule', models.CharField(max_length=10, null=True)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('photo', models.CharField(max_length=50, null=True)),
                ('Nummaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatSevApp.officier')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('NumP', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_Naissance', models.CharField(max_length=10, null=True)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Sexe', models.CharField(max_length=15)),
                ('Date_Naissance', models.DateField()),
                ('Heure_Naissance', models.TimeField()),
                ('Lieu_de_Naissance', models.CharField(max_length=20)),
                ('Pays_de_Naissance', models.CharField(default='', max_length=20)),
                ('Situation_Marital', models.BooleanField(default=True)),
                ('Adress', models.CharField(max_length=30)),
                ('Etat_de_vie', models.BooleanField(default=True)),
                ('Profession', models.CharField(max_length=50, null=True)),
                ('NumCommune', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='etatSevApp.commune')),
                ('NumMere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mere', to='etatSevApp.personne')),
                ('NumPere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Pere', to='etatSevApp.personne')),
            ],
        ),
        migrations.CreateModel(
            name='TravailleI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_dub', models.DateField()),
                ('Date_Fin', models.DateField(null=True)),
                ('NumAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etatSevApp.agent_consulat')),
                ('NumB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etatSevApp.consulat')),
            ],
        ),
        migrations.CreateModel(
            name='Travaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_dub', models.DateField()),
                ('Date_Fin', models.DateField(null=True)),
                ('NumB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etatSevApp.bureau')),
                ('NumOff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etatSevApp.officier')),
            ],
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('NumRegistre', models.AutoField(primary_key=True, serialize=False)),
                ('Annee', models.CharField(default='', max_length=10)),
                ('Type', models.CharField(max_length=10)),
                ('NumBureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etatSevApp.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='PersonneDeces',
            fields=[
                ('NumD', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Deces', models.DateField()),
                ('Heure_Deces', models.TimeField()),
                ('Cause_Deces', models.CharField(max_length=50)),
                ('Lieu_de_Deces', models.CharField(max_length=20)),
                ('NumDeclarant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dec', to='etatSevApp.personne')),
                ('NumP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatSevApp.personne')),
                ('NumRegistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatSevApp.registre')),
            ],
        ),
        migrations.AddField(
            model_name='personne',
            name='NumRegistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatSevApp.registre'),
        ),
        migrations.AddField(
            model_name='personne',
            name='NumTet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tet', to='etatSevApp.personne'),
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('NumF', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Mariage', models.DateField()),
                ('lieu_Mariage', models.CharField(max_length=50)),
                ('NumFamme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Famme', to='etatSevApp.personne')),
                ('NumHomme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Homme', to='etatSevApp.personne')),
                ('NumRegistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatSevApp.registre')),
                ('NumTem1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tem1', to='etatSevApp.personne')),
                ('NumTem2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tem2', to='etatSevApp.personne')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='NumMaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatSevApp.officier'),
        ),
        migrations.AddField(
            model_name='bureau',
            name='NumC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatSevApp.commune'),
        ),
    ]
