# Generated by Django 4.1.4 on 2023-01-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etatSevApp', '0043_remove_famille_numregistre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='engeristrement',
        ),
    ]
